apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: alpha
  name: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alpha
  template:
    metadata:
      labels:
        io.kompose.service: alpha
    spec:
      containers:
      - env:
        - name: BOOT_MONGO_URI
          value: app
        image: deltan123/alpha:0.0.1-SNAPSHOT
        name: alpha
        ports:
        - containerPort: 8001
      restartPolicy: Always
