apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: alpha
  name: alpha
spec:
  type: LoadBalancer
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    io.kompose.service: alpha
